"""Regenerate embedded modules/manifest in lab_day2.ipynb after editing code/*.py."""
import base64
import hashlib
import json
from pathlib import Path


def sync():
    root = Path(__file__).resolve().parent
    path = root / "lab_day2.ipynb"
    nb = json.loads(path.read_text(encoding="utf-8"))
    modules = ["runtime.py","dataset.py","model.py","losses.py","benchmark.py",
               "inference.py","train.py","runner.py","eval.py"]
    sources = {name:(root/name).read_bytes() for name in modules}
    # Exact bytes preserve the immutable evaluator, including line endings.
    payload = {name:base64.b64encode(raw).decode("ascii") for name,raw in sources.items()}
    embedded = ("# Embedded source: generated by code/sync_notebook.py\n"
                "import base64\nEMBEDDED_SOURCE = " + json.dumps(payload, indent=2) + "\n"
                "for name, encoded in EMBEDDED_SOURCE.items():\n"
                "    (CODE_DIR / name).write_bytes(base64.b64decode(encoded))\n"
                "print(f'Wrote {len(EMBEDDED_SOURCE)} modules to {CODE_DIR}', flush=True)\n")
    hashes = {name:hashlib.sha256(raw).hexdigest() for name,raw in sources.items()}
    for cell in nb["cells"]:
        marker = cell.get("metadata",{}).get("day2")
        if marker == "embedded":
            cell["source"] = embedded.splitlines(keepends=True)
        if marker == "imports":
            text = "".join(cell["source"])
            start = text.index("EXPECTED_SOURCE_SHA256 = ")
            end = text.index("\nfor name, expected",start)
            text = text[:start] + "EXPECTED_SOURCE_SHA256 = " + json.dumps(hashes,indent=2) + text[end:]
            cell["source"] = text.splitlines(keepends=True)
        if cell["cell_type"] == "code":
            cell["outputs"],cell["execution_count"] = [],None
    nb["metadata"] = {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},
                      "language_info":{"name":"python","version":"3"}}
    path.write_text(json.dumps(nb,indent=1,ensure_ascii=False)+"\n",encoding="utf-8")
    print(f"Synced {len(modules)} modules into {path}")


if __name__ == "__main__":
    sync()
